/**
 * Seed catalogue for Siva Sarvesh Crackers, taken from the
 * "Discount Rate Price List 2026" PDF.
 *
 * `rate` is the printed Rate and is the price the customer pays (discount 0).
 * Tamil names are copied exactly as printed in the PDF.
 *
 * Row format: [product name, Tamil name, unit, rate]
 */

export const categories = [
  { slug: 'single-sound-crackers', name: 'Single Sound Crackers', tamil: 'ஒற்றை வெடிகள்', discount: 0, products: [
    ['2¾" Kuruvi', '2¾" குருவி', '1 PKT', 35],
    ['3½" Lakshmi', '3½" லட்சுமி', '1 PKT', 75],
    ['4" Lakshmi', '4" லட்சுமி', '1 PKT', 125],
    ['4" Deluxe Lakshmi', '4" டீலக்ஸ் லட்சுமி', '1 PKT', 150],
    ['Gold Lakshmi', 'கோல்டு லட்சுமி', '1 PKT', 160],
    ['5" Bahubali', '5" பாகுபலி', '1 PKT', 200],
    ['5" Jallikattu', '5" ஜல்லிக்கட்டு', '1 PKT', 200],
    ['5" Colour Vedi', '5" கலர் வெடி', '1 PKT', 300],
    ['6" Kumki', '6" கும்கி', '1 PKT', 200],
    ['2 Sound Crackers', '2 சவுண்ட் கிராக்கர்ஸ்', '1 PKT', 250],
    ['3 Sound Crackers', '3 சவுண்ட் கிராக்கர்ஸ்', '1 PKT', 250],
  ] },
  { slug: 'ground-chakkars', name: 'Ground Chakkars', tamil: 'தரைச்சக்கரம்', discount: 0, products: [
    ['Ground Chakkar Big (10 Pcs)', 'சக்கரம் சிறியது 10 பீஸ்', '1 BOX', 200],
    ['Ground Chakkar Small (25 Pcs)', 'சக்கரம் சிறியது 25 பீஸ்', '1 BOX', 500],
    ['Ground Chakkar Asoka (10 Pcs)', 'சக்கரம் அசோகா 10 பீஸ்', '1 BOX', 400],
    ['Ground Chakkar Special (10 Pcs)', 'சக்கரம் ஸ்பெஷல் 10 பீஸ்', '1 BOX', 500],
    ['Ground Chakkar Deluxe (10 Pcs)', 'சக்கரம் டீலக்ஸ் 10 பீஸ்', '1 BOX', 700],
    ['Winner Special (10 Pcs)', 'வின்னர் ஸ்பெஷல் 10 பீஸ்', '1 BOX', 1000],
    ['Winner Deluxe (10 Pcs)', 'வின்னர் டீலக்ஸ் 10 பீஸ்', '1 BOX', 1250],
    ['Whistling Wheel (5 Pcs)', 'விசிலிங் வீல் 5 பீஸ்', '1 BOX', 800],
    ['4×4 Lotus Wheel (5 Pcs)', '4X4 லோட்டஸ் வீல்', '1 BOX', 1000],
  ] },
  { slug: 'flower-pots', name: 'Flower Pots', tamil: 'பூச்சட்டி', discount: 0, products: [
    ['Flower Pot Small (10 Pcs)', 'பூச்சட்டி சிறியது', '1 BOX', 200],
    ['Flower Pot Big (10 Pcs)', 'பூச்சட்டி பெரியது', '1 BOX', 300],
    ['Flower Pot Special (10 Pcs)', 'பூச்சட்டி ஸ்பெஷல்', '1 BOX', 450],
    ['Flower Pot Asoka (10 Pcs)', 'பூச்சட்டி அசோகா', '1 BOX', 600],
    ['Flower Pot Jersey (5 Pcs)', 'பூச்சட்டி ஜெர்ஸி', '1 BOX', 900],
    ['Flower Pot Giant (10 Pcs)', 'பூச்சட்டி ஜெயின்ட்', '1 BOX', 100],
    ['Colour Koti (10 Pcs)', 'கலர் கோட்டி', '1 BOX', 100],
    ['Colour Koti Special (10 Pcs)', 'கலர் கோட்டி ஸ்பெஷல்', '1 BOX', 1250],
    ['Multi Colour Giant', 'மல்டி கலர் ஜெயின்ட்', '1 BOX', 1750],
    ['Flower Pot Super Deluxe (2 Pcs)', 'பூச்சட்டி சூப்பர் டீலக்ஸ்', '1 BOX', 750],
    ['Silver Koti', 'சில்வர் கோட்டி', '1 BOX', 1750],
    ['Flower Pot Deluxe (5 Pcs)', 'பூச்சட்டி டீலக்ஸ்', '1 BOX', 1250],
    ['Colour Koti Deluxe (10 Pcs)', 'கலர்கோட்டி டீலக்ஸ்', '1 BOX', 1750],
    ['Colour Koti Super Deluxe (10 Pcs)', 'கலர்கோட்டி சூப்பர் டீலக்ஸ்', '1 BOX', 2000],
    ['Tri Colour (5 Pcs)', 'த்ரி கலர்', '1 BOX', 1750],
  ] },
  { slug: 'pencils', name: 'Pencils', tamil: 'பென்சில்', discount: 0, products: [
    ['7 cm Pencil', '7 செ.மீ பென்சில்', '1 BOX', 125],
    ['10 cm Pencil', '10 செ.மீ பென்சில்', '1 BOX', 175],
    ['12 cm Pencil', '12 செ.மீ பென்சில்', '1 BOX', 225],
    ['15 cm Pencil', '15 செ.மீ பென்சில்', '1 BOX', 300],
    ['18 cm Pencil', '18 செ.மீ பென்சில்', '1 BOX', 400],
    ['SS Pyro Colour Pencil (2 Pcs)', 'பைரோ கலர் பென்சில்', '1 BOX', 1250],
    ['Selfie Stick (5 Pcs)', 'செல்பி ஸ்டிக்', '1 BOX', 1000],
    ['Navarang Pencil (5 Pcs)', 'நவ்ரங் பென்சில்', '1 BOX', 800],
    ['Sivakasi Pencil (2 Pcs)', 'சிவகாசி பென்சில்', '1 BOX', 1000],
    ['5G Gun', '5ஜி கன்', '1 BOX', 1250],
  ] },
  { slug: 'twinkling-stars', name: 'Twinkling Stars', tamil: 'சாட்டை', discount: 0, products: [
    ['1½" Twinkling Star', "1 1/2' சாட்டை", '1 BOX', 150],
    ['4" Twinkling Star', '4" சாட்டை', '1 BOX', 300],
  ] },
  { slug: 'bombs', name: 'Bombs', tamil: 'பாம்ப்ஸ்', discount: 0, products: [
    ['Bullet Bomb', 'புல்லட் பாம்', '1 BOX', 150],
    ['Atom Bomb', 'ஆட்டம் பாம்', '1 BOX', 275],
    ['Hydro Bomb', 'ஹைட்ரோ பாம்', '1 BOX', 350],
    ['King of King Bomb', 'கிங் ஆப் கிங் பாம்', '1 BOX', 600],
    ['Classic Bomb', 'கிளாசிக் பாம்', '1 BOX', 750],
    ['Agni Bomb', 'அக்னி பாம்', '1 BOX', 1250],
    ['Digital Bomb', 'டிஜிட்டல் பாம்ப்', '1 BOX', 1500],
  ] },
  { slug: 'electric-crackers', name: 'Electric Crackers', tamil: 'எலக்ட்ரிக் கிராக்கர்ஸ்', discount: 0, products: [
    ['28 Chorsa', '28 சோர்சா', '1 BOX', 75],
    ['28 Giant', '28 ஜெயிண்ட்', '1 BOX', 100],
    ['56 Giant', '56 ஜெயிண்ட்', '1 BOX', 200],
    ['24 Bada', '24 படா', '1 BOX', 250],
    ['50 Bada', '50 படா', '1 BOX', 750],
    ['100 Bada', '100 படா', '1 BOX', 1250],
  ] },
  { slug: 'chain-crackers', name: 'Chain Crackers', tamil: 'செயின் கிராக்கர்ஸ்', discount: 0, products: [
    ['100 Chain', '100 செயின்', '1 BOX', 175],
    ['200 Chain', '200 செயின்', '1 BOX', 350],
    ['300 Chain', '300 செயின்', '1 BOX', 600],
    ['600 Chain', '600 வாலா', '1 BOX', 100],
    ['1K Chain', '1 கே செயின்', '1 BOX', 1400],
    ['2K Chain', '2 கே செயின்', '1 BOX', 2800],
    ['5K Chain', '5 கே செயின்', '1 BOX', 7000],
    ['10K Chain', '10 கே செயின்', '1 BOX', 14000],
    ['1K Chain - Off Count', '1கே செயின்-ஆப் கவுண்ட்', '1 BOX', 800],
    ['2K Chain - Off Count', '2கே செயின்-ஆப் கவுண்ட்', '1 BOX', 1600],
    ['5K Chain - Off Count', '5கே செயின்-ஆப் கவுண்ட்', '1 BOX', 4000],
    ['10K Chain - Off Count', '10கே செயின்-ஆப் கவுண்ட்', '1 BOX', 8000],
  ] },
  { slug: 'bijili-crackers', name: 'Bijili Crackers', tamil: 'பிஜிலி கிராக்கர்ஸ்', discount: 0, products: [
    ['Red Bijili (50 Pcs)', 'ரெட் பிஜிலி 50 பீஸ்', '1 BAG', 75],
    ['Red Bijili (100 Pcs)', 'ரெட் பிஜிலி 100 பீஸ்', '1 BAG', 150],
    ['Striped Bijili (50 Pcs)', 'வரி பிஜிலி 50 பீஸ்', '1 BAG', 80],
    ['Striped Bijili (100 Pcs)', 'வரி பிஜிலி 100 பீஸ்', '1 BAG', 160],
    ['Boom Boom (25 Pcs)', 'பிஜிலி ஸ்பெஷல்', '1 BOX', 1250],
  ] },
  { slug: 'fancy-crackers', name: 'Fancy Crackers', tamil: 'பேன்சி கிராக்கர்ஸ்', discount: 0, products: [
    ['Light Mix (2 Pcs)', 'லைட் மிக்ஸ் (2 பீஸ்)', '1 BOX', 600],
    ['Chotta Fancy', 'சோட்டா பேன்சி', '1 BOX', 200],
    ['2½" Pipe Fancy', '2 1/2 பைப் பேன்சி', '1 BOX', 500],
    ['2½" Pipe Fancy (3 Pcs)', '2 1/2 பைப் பேன்சி (3)', '1 BOX', 1500],
    ['3½" Fancy Pipe', '3 1/2 பைப் பேன்சி', '1 BOX', 1250],
    ['3½" Fancy Pipe Niagara Falls', '3 1/2 பேன்சி பைப் நயகரா', '1 BOX', 1500],
    ['3½" Fancy Pipe Special', '3 1/2 பைப் ஸ்பெஷல்', '1 BOX', 1500],
    ['3½" Fancy Pipe Special 7 Step', '3 1/2 பேன்சி பைப் ஸ்பெஷல்', '1 BOX', 1750],
    ['3½" Fancy Pipe Special (2 Pcs)', '3 1/2 பேன்சி பைப் 2 பீஸ்', '1 BOX', 3500],
    ['4" Fancy Pipe Special', '4" பைப் ஸ்பெஷல்', '1 BOX', 2000],
    ['4" Fancy Pipe Double Ball', '4" பேன்சில் டபுள் பால்', '1 BOX', 2000],
    ['4" Fancy Pipe Special (2 Pcs)', '4" பேன்சி பைப் ஸ்பெஷல்', '1 BOX', 4000],
    ['5" Fancy Pipe Special (2 Pcs)', '5" பேன்சி பைப் ஸ்பெஷல்', '1 BOX', 4500],
    ['6" Fancy Pipe Special (2 Pcs)', '6" பேன்சி பைப் ஸ்பெஷல்', '1 BOX', 5000],
  ] },
  { slug: 'multi-colour-shots', name: 'Multi Colour Shots', tamil: 'மல்டி கலர் சாட்ஸ்', discount: 0, products: [
    ['Penta (5 Pcs)', 'பென்டா (5 பீஸ்)', '1 BOX', 1250],
    ['7 Shot (5 Pcs)', '7 சாட் (5பீஸ்)', '1 BOX', 600],
    ['Colour Celebration (5 Pcs)', 'கலர் செலிபிரேசன்', '1 BOX', 1250],
    ['12 Shot Crackling', '12 சாட் கிராக்ளிங்', '1 BOX', 1000],
    ['12 Shot Colour', '12 சாட் கலர்', '1 BOX', 1000],
    ['25 Shot Crackling', '25 சாட் கிராக்ளிங்', '1 BOX', 1500],
    ['21 Shot (1 Shot 5 Ball - 105 Balls)', '21 சாட்', '1 BOX', 3000],
    ['30 Shot Colour', '30 சாட் கலர்', '1 BOX', 2000],
    ['60 Shot Colour', '60 சாட் கலர்', '1 BOX', 4000],
    ['120 Shot Colour', '120 சாட் கலர்', '1 BOX', 8000],
    ['240 Shot Colour', '240 சாட் கலர்', '1 BOX', 16000],
  ] },
  { slug: 'fancy-fountains', name: 'Fancy Fountains', tamil: 'பேன்சி வெடிகள்', discount: 0, products: [
    ['Colour Rain (5 Pcs)', 'கலர் மழை', '1 BOX', 600],
    ['Peacock Feathers (5 Pcs)', 'பீகாக் பெதர்', '1 BOX', 600],
    ['Golden Globe (5 Pcs)', 'கோல்டன் குளோப்', '1 BOX', 600],
    ['Fountain Shower (5 Pcs)', 'பவுண்டைன் ஷோர்', '1 BOX', 600],
    ['Fox Star', 'பாக்ஸ் ஸ்டார்', '1 BOX', 750],
    ['Sing Pop', 'சிங் பாப்', '1 BOX', 1000],
    ['Magic Peacock', 'மேஜிக் பீகாக்', '1 BOX', 1000],
    ['Dancing Peacock', 'டான்சிங் பீகாக்', '1 BOX', 1000],
    ['Bada Peacock', 'படா பீகாக்', '1 BOX', 2000],
    ['90 Watts Magic Wala (3 Pcs)', '90 வாட்ஸ் மேஜிக் வாலா', '1 BOX', 750],
    ['Magic Sound Magic Wala', 'மேஜிக் சவுண்ட் மேஜிக் வாலா', '1 BOX', 1000],
    ['Coke (5 Pcs)', 'கோக் (5 பீஸ்)', '1 BOX', 600],
    ['Fanta or Thums Up (5 Pcs)', 'பேன்டா தம்ஸ்', '1 BOX', 750],
    ['Jelly Pops (5 Pcs)', 'ஜெல்லி பாப்ஸ்', '1 BOX', 1000],
    ['Sprite or Coca-Cola (5 Pcs)', 'ஸ்பிரிட் கோகோகோலா', '1 BOX', 1250],
    ['H2O Falls Red or Green', 'ஹைச் டூ ஓ அருவி', '1 BOX', 1000],
    ['4.5 Fountain Tin Colour Mix', '4.5 பவுண்டைன் டின் கலர் மிக்ஸ்', '1 BOX', 1000],
    ['Cool Drinks Shower', 'கூல் டிரிங்க்ஸ்', '1 BOX', 750],
    ['Sunfeast Colour Fountain (5 Pcs)', 'சன்பீஸ்ட் கலர் பவுண்டைன்', '1 BOX', 800],
    ['Croods Fountain', 'க்ரூட்ஸ் பவுண்டைன்', '1 BOX', 1000],
    ['Mini Bulls (1 Pc)', 'மினி புல்ஸ்', '1 BOX', 250],
    ['Lolli Pop (5 Pcs)', 'லாலி பாப்', '1 BOX', 1250],
    ['Rainbow Smoke (3 Pcs)', 'ரெயின்போ ஸ்மோக்', '1 BOX', 1000],
    ['Kung Fu Panda (1 Pc)', 'குங்பூ பேன்டா', '1 BOX', 300],
    ['Mini Bulls (5 Pcs)', 'மினி புல்ஸ்', '1 BOX', 1250],
    ['Bat & Ball', 'பேட் & பால்', '1 BOX', 1250],
    ['Wire Chakkaram Hand Chakkar', 'வயர் சக்கரம்', '1 BOX', 1000],
    ['Kung Fu Panda (5 Pcs)', 'குங்பூ பேன்டா 5 பீஸ்', '1 BOX', 1500],
    ['Water Falls Fountain (1 Pc)', 'வாட்டர் பால்ஸ் பவுண்டைன்', '1 BOX', 1000],
    ['Water Queen', 'வாட்டர் குயின்', '1 BOX', 1000],
    ['Helicopter', 'ஹெலிகாப்டர்', '1 BOX', 600],
    ['Jasmine Flower (2 Pcs)', 'ஜேஸ்மின் ப்ளவர்', '1 BOX', 1250],
    ['Peacock Tail (2 Pcs)', 'பீகாக் டெயில்', '1 BOX', 1250],
  ] },
  { slug: 'kids-special', name: 'Kids Special', tamil: 'குழந்தை ஸ்பெஷல்', discount: 0, products: [
    ['Snake Tablet', 'பாம்பு மாத்திரை', '1 BOX', 100],
    ['Roll Cap', 'ரோல் கேப்', '1 BOX', 600],
    ['Stone', 'ஸ்டோன்', '1 BOX', 40],
    ['Stone Green', 'ஸ்டோன் பச்சை', '1 BOX', 100],
    ['Gee Boom Baa', 'ஜீ பூம் பா', '1 BOX', 40],
    ['Cartoon Small (10 Pcs)', 'கார்ட்டூன் ஸ்மால்', '1 BOX', 100],
    ['Cartoon Big (10 Pcs)', 'கார்ட்டூன் பிக்', '1 BOX', 250],
    ['Kit Kat (10 Pcs)', 'கிட் காட்', '1 BOX', 125],
    ['Butterfly (10 Pcs)', 'பட்டர் ப்ளை', '1 BOX', 400],
    ['Bambaram', 'பம்பரம்', '1 BOX', 600],
    ['Photo Flash (5 Pcs)', 'போட்டோ ப்பிளாஷ்', '1 BOX', 500],
    ['Photo Flash Red or Green (5 Pcs)', 'போட்டோ ப்ளாஷ்', '1 BOX', 600],
    ['Tim Tam (10 Pcs)', 'டிம் டாம்', '1 BOX', 300],
  ] },
  { slug: 'rockets', name: 'Rockets', tamil: 'ராக்கெட்', discount: 0, products: [
    ['Rocket Bomb (10 Pcs)', 'ராக்கெட் பாம்ப்', '1 BOX', 150],
    ['Rocket Bomb Special (10 Pcs)', 'ராக்கெட் பாம்ப் ஸ்பெசல்', '1 BOX', 400],
    ['Musical Rocket', 'மியூசிக்கல் ராக்கெட்', '1 BOX', 750],
    ['Lunik Rocket (10 Pcs)', 'லூனிக் ராக்கெட்', '1 BOX', 1000],
    ['2 Sound Rocket (10 Pcs)', '2 சவுண்ட் ராக்கெட்', '1 BOX', 1000],
    ['Whistling Rocket (10 Pcs)', 'விஸ்லிங் ராக்கெட்', '1 BOX', 1000],
  ] },
  { slug: 'paper-shots', name: 'Paper Shots', tamil: 'பேப்பர் சாட்ஸ்', discount: 0, products: [
    ['Magic Treat Currency', 'மேஜிக் ட்ரீட் கரன்சி', '1 BOX', 1500],
    ['¼ Kilo Paper Bomb', '1/4 கிலோ பேப்பர் பாம்', '1 BOX', 350],
    ['½ Kilo Paper Bomb', '1/2 கிலோ பேப்பர் பாம்', '1 BOX', 700],
    ['1 Kilo Paper Bomb', '1 கிலோ பேப்பர் பாம்', '1 BOX', 1400],
  ] },
  { slug: 'laddu-flower-pots', name: 'Laddu Flower Pots', tamil: 'லட்டு பிளவர் பாட்ஸ்', discount: 0, products: [
    ['2 in 1 Laddu (10 Pcs)', '2 இன் 1 (10 பீஸ்)', '1 BOX', 2500],
    ['Colour Changing Laddu (5 Pcs)', 'கலர் சேஞ்சிங் லட்டு', '1 BOX', 2500],
    ['Deluxe Laddu (4 Pcs)', 'கலர் சேஞ்சிங் டீலக்ஸ்', '1 BOX', 3000],
  ] },
  { slug: 'sparklers', name: 'Sparklers', tamil: 'கம்பி மத்தாப்புகள்', discount: 0, products: [
    ['7 cm Electric Sparklers', '7 செ.மீ சாதா கம்பி', '1 BOX', 75],
    ['7 cm Colour Sparklers', '7 செ.மீ கலர் கம்பி', '1 BOX', 75],
    ['7 cm Green Sparklers', '7 செ.மீ பச்சை கம்பி', '1 BOX', 75],
    ['7 cm Red Sparklers', '7 செ.மீ சிவப்பு கம்பி', '1 BOX', 75],
    ['10 cm Electric Sparklers', '10 செ.மீ சாதா கம்பி', '1 BOX', 100],
    ['10 cm Colour Sparklers', '10 செ.மீ கலர் கம்பி', '1 BOX', 100],
    ['10 cm Green Sparklers', '10 செ.மீ பச்சை கம்பி', '1 BOX', 100],
    ['10 cm Red Sparklers', '10 செ.மீ சிவப்பு கம்பி', '1 BOX', 100],
    ['12 cm Electric Sparklers', '12 செ.மீ சாதா கம்பி', '1 BOX', 150],
    ['12 cm Colour Sparklers', '12 செ.மீ கலர் கம்பி', '1 BOX', 150],
    ['12 cm Green Sparklers', '12 செ.மீ பச்சை கம்பி', '1 BOX', 150],
    ['12 cm Red Sparklers', '12 செ.மீ சிவப்பு கம்பி', '1 BOX', 150],
    ['15 cm Electric Sparklers', '15 செ.மீ சாதா கம்பி', '1 BOX', 250],
    ['15 cm Colour Sparklers', '15 செ.மீ கலர் கம்பி', '1 BOX', 250],
    ['15 cm Green Sparklers', '15 செ.மீ பச்சை கம்பி', '1 BOX', 250],
    ['15 cm Red Sparklers', '15 செ.மீ சிவப்பு கம்பி', '1 BOX', 250],
    ['30 cm Electric Sparklers', '30 செ.மீ சாதா கம்பி', '1 BOX', 250],
    ['30 cm Colour Sparklers', '30 செ.மீ கலர் கம்பி', '1 BOX', 250],
    ['30 cm Green Sparklers', '30 செ.மீ பச்சை கம்பி', '1 BOX', 250],
    ['30 cm Red Sparklers', '30 செ.மீ சிவப்பு கம்பி', '1 BOX', 250],
    ['50 cm Electric Sparklers', '50 செ.மீ சாதா கம்பி', '1 BOX', 1000],
    ['50 cm Colour Sparklers', '50 செ.மீ கலர் கம்பி', '1 BOX', 1100],
  ] },
  { slug: 'colour-matches', name: 'Colour Matches', tamil: 'கலர் மேட்சஸ்', discount: 0, products: [
    ['Sachin Pocket (3 Pcs)', 'சச்சின் (3 பீஸ்)', '1 PKT', 100],
    ['Sachin Pocket (5 Pcs)', 'சச்சின் (5 பீஸ்)', '1 PKT', 175],
    ['Sachin Box (10 Pcs)', 'சச்சின் பாக்ஸ்', '1 BOX', 350],
    ['Lion Laptop (10 Pcs)', 'லயன் லேப்டாப்', '1 BOX', 800],
    ['Royal Laptop (10 Pcs)', 'ராயல் லேப்டாப்', '1 BOX', 1000],
  ] },
  { slug: 'music-crayon', name: 'Music Crayon', tamil: 'மியூசிக் க்ரையன்', discount: 0, products: [
    ['Crayon Small (5 Pcs)', 'க்ரையன் சுமால் (5 பீஸ்)', '1 BOX', 750],
    ['Crayon Big (3 Pcs)', 'க்ரையன் பிக் (3 பீஸ்)', '1 BOX', 1000],
  ] },
  { slug: 'gift-boxes', name: 'Gift Boxes (Net Rate)', tamil: 'கிப்ட் பாக்ஸ்', discount: 0, products: [
    ['17 Item Box', '17 அயிட்டம்', '1 BOX', 250],
    ['21 Item Box', '21 அயிட்டம்', '1 BOX', 300],
    ['27 Item Box', '27 அயிட்டம்', '1 BOX', 350],
    ['31 Item Box', '31 அயிட்டம்', '1 BOX', 400],
    ['35 Item Box', '35 அயிட்டம்', '1 BOX', 500],
    ['40 Item Box', '40 அயிட்டம்', '1 BOX', 650],
    ['45 Item Box', '45 அயிட்டம்', '1 BOX', 800],
    ['50 Item Box', '50 அயிட்டம்', '1 BOX', 1000],
    ['61 Item Family Box', 'பேமிலி பாக்ஸ்', '1 BOX', 1600],
    ['Combo Pack Silver', 'காம்போ பேக் சில்வர்', '1 BOX', 2500],
    ['Combo Pack Gold', 'காம்போ பேக் கோல்ட்', '1 BOX', 3500],
    ['Combo Pack Diamond', 'காம்போ பேக் டைமண்ட்', '1 BOX', 5000],
  ] },
];

/** Round to 2 decimals using integer paise math. */
function sellingPriceFor(rate, discount) {
  return Math.round(rate * 100 * (100 - discount) / 100) / 100;
}

/** Flattens the catalogue into DB-ready rows with stable product codes (SSC001...). */
export function buildSeedRows() {
  let serial = 0;
  const categoryRows = [];
  const productRows = [];
  categories.forEach((category, categoryIndex) => {
    categoryRows.push({
      name: category.name,
      tamilName: category.tamil,
      slug: category.slug,
      displayOrder: categoryIndex + 1,
    });
    category.products.forEach(([name, tamil, unit, rate]) => {
      serial += 1;
      productRows.push({
        productCode: `SSC${String(serial).padStart(3, '0')}`,
        productName: name,
        tamilName: tamil,
        categorySlug: category.slug,
        unit,
        originalPrice: rate,
        discountPercentage: category.discount,
        sellingPrice: sellingPriceFor(rate, category.discount),
        displayOrder: serial,
      });
    });
  });
  return { categoryRows, productRows };
}
